from pathlib import Path 


MAINCAM_INDEX = 1
MAINCAM_WIDTH = 3840
MAINCAM_HEIGHT = 2160
BLUR_COEFFICIENT = 15
ARMCAM_INDEX = 2
ARMCAM_WIDTH = 640
ARMCAM_HEIGHT = 480
ARMCAM_OFFSET = 265
ARMCAM_MISDETECTION_THRESHOLD = 7
CARDNET_PATH = Path(__file__).parent.parent / "model" / "cardnet-20ep.pt"
CARDNET_CONFIDENCE = 0.38
BIDDING_BOX_NET_PATH = Path(__file__).parent.parent / "model" / "bidding-box-net-40ep.pt"
BIDDING_BOX_NET_CONFIDENCE = 0.38
ARDUINO_BAUDRATE = 115200

CARD_AREA = 3000
BKG_THRESH = 110
COALESCE_DISTANCE_SQUARED = 900
UPSIDE_DOWN_THRESH = 150

MAD_THRESHOLD = 2
